import React, { createContext, useState, useContext, useEffect } from 'react';

export const translations = {
  en: {
    sidebar: {
      home: 'Home',
      wallet: 'Wallet',
      trading: 'Trading',
      physical: 'Physical',
      loan: 'Loan',
      staking: 'Staking',
      account: 'Account',
      statement: 'Statement',
      guide: 'Guide',
      admin: 'Admin',
      security: 'Security',
      security_desc: 'Your assets are protected with institutional-grade security protocols.',
      bank_grade_security: 'Bank-Grade Security',
    },
    login: {
      company_name: 'EVE FINANCE',
      company_tagline: 'Premium Exchange',
      future_of_trading: 'The Future of',
      precious_metals: 'Precious Metals',
      trading: 'Trading',
      platform_description: 'Experience the world\'s most advanced precious metals platform. Trade gold, silver, platinum, and palladium with institutional-grade security and lightning-fast execution.',
      bank_grade_security: 'Bank-Grade Security & Insurance',
      instant_trading: 'Instant Trading & Real-Time Pricing',
      eve_rewards: 'EVE Rewards - Get 100 EVE per $1 Fee',
      account_access: 'Account Access',
      login_description: 'Please log in to access your account and manage your KYC verification',
      login_with_google: 'Login with Google',
      secure_auth: 'Secure authentication powered by Google',
      military_encryption: 'Protected by military-grade encryption',
      data_safe: 'Your data is safe with us'
    },
    home: {
      market_alert: 'GOLD +50% IN 2025',
      record_breaking: 'Record Breaking Performance',
      golden_age: 'The Golden Age',
      is_here: 'Is Here',
      surge_2025: 'In 2025, GOLD surged over 50%, stunning global markets and reigniting investor excitement worldwide.',
      inflation_fears: 'As inflation fears, geopolitical tension, and fiat uncertainty intensified, gold once again proved its timeless value. Traders, institutions, and retail investors rushed in, driving prices to record highs. The rally turned gold into the best-performing asset of the year.',
      safe_haven: 'From safe haven to profit engine, gold\'s resurgence lit up portfolios and headlines alike — and it\'s not done yet.',
      golden_age_beginning: 'The golden age may just be beginning.',
      start_trading: 'Start Trading Gold',
      view_prices: 'View Live Prices',
      bank_grade_security: 'Bank-Grade Security',
      instant_trading: 'Instant Trading',
      live_market_data: 'Live Market Data',
      market_leaders: '🏆 2025 Market Leaders',
      metals_performance: 'Precious Metals Performance',
      witness_surge: 'Witness the historic surge that\'s reshaping investment portfolios worldwide. These aren\'t just metals — they\'re the foundation of financial security.',
      best_performer: '🔥 Best Performer 2025',
      strong_rally: '📈 Strong Rally',
      rising_fast: '⚡ Rising Fast',
      steady_growth: '💎 Steady Growth',
      gold_desc: 'The year\'s top performer with unprecedented 50+ surge, proving its enduring value as the ultimate store of wealth.',
      silver_desc: 'Following gold\'s momentum with industrial demand and monetary appeal driving significant gains.',
      platinum_desc: 'Benefiting from supply constraints and automotive recovery, showing renewed investor interest.',
      palladium_desc: 'Tech sector demand and limited supply continue to support elevated price levels.',
      zero_fees: 'Trade all metals with zero fees on your first $10,000',
      revolutionary_platform: '⚡ Revolutionary Platform',
      built_future: 'Built for the Future',
      advanced_platform: 'Experience the most advanced precious metals platform ever created. Every feature designed for maximum performance and security.',
      instant_gold_trading: 'Instant Gold Trading',
      execute_trades: 'Execute trades in milliseconds with live market pricing. No delays, no slippage — just pure speed.',
      asset_backed_lending: 'Asset-Backed Lending',
      unlock_liquidity: 'Unlock liquidity without selling. Borrow up to 80% against your precious metals at competitive rates.',
      fort_knox_security: 'Fort Knox Security',
      military_grade: 'Military-grade protection with cold storage, insurance, and multi-signature protocols.',
      yield_generation: 'Yield Generation',
      stake_metals: 'Stake your metals and earn passive income. Turn your portfolio into a profit engine.',
      lightning_fast: 'Lightning Fast',
      fast_trading: '24/7 trading with sub-second execution. The fastest precious metals platform on earth.',
      always_available: 'Always Available',
      trade_anytime: 'Trade anytime, anywhere. Our platform never sleeps, so your opportunities never wait.',
      join_gold_rush: 'Join the Gold Rush',
      dont_miss: 'Don\'t miss out on the biggest precious metals opportunity of the decade. Start trading today.',
      active_traders: '50,000+ Active Traders',
      volume_traded: '$2.8B+ Volume Traded',
      uptime: '99.9% Uptime',
      eve_revolution: '🚀 The EVE Revolution',
      introducing_eve: 'Introducing EVE Token',
      eve_subtitle: 'The world\'s first precious metals trading reward token. Every trade earns you EVE—your gateway to the future of finance.',
      earn_eve: 'Earn EVE Tokens',
      earn_eve_desc: 'Get 100 EVE tokens for every $1 in trading fees. Transform your trading activity into valuable digital assets.',
      blockchain_ready: 'Blockchain Ready',
      blockchain_desc: 'EVE is designed for the future. Full blockchain integration and self-custody capabilities coming soon.',
      global_exchange: 'Global Exchange Listing',
      exchange_desc: 'Our roadmap includes listing EVE on major worldwide exchanges, unlocking global liquidity and market value.',
      ecosystem_utility: 'Ecosystem Utility',
      utility_desc: 'Use EVE for reduced fees, governance voting, and exclusive access to premium features and services.',
      start_earning: 'Start Earning EVE',
      learn_about_eve: 'Learn About EVE',
      eve_stats_earned: '2.5M+ EVE Earned',
      eve_stats_traders: '15,000+ EVE Holders',
      eve_stats_value: 'Growing Daily'
    },
    wallet: {
      title: 'Portfolio Wallet',
      subtitle: 'Manage your precious metals and currencies',
      deposit: 'Deposit',
      kyc_required_tooltip: 'Please complete KYC to deposit funds.',
      refresh: 'Refresh',
      total_portfolio_value: 'Total Portfolio Value',
      change_24h: '24h Change',
      active_assets: 'Active Assets',
      asset_balances: 'Asset Balances',
      live_prices: 'Live Prices',
      quick_actions: 'Quick Actions',
      transaction_history: 'Transaction History',
      requests_title: 'Deposit/Withdrawal Requests',
    },
    chatbot: {
      greeting_title: "Hello! I'm",
      greeting_subtitle: "Your personal assistant for today. How can I help you?",
      input_placeholder: "Ask about trading, loans, or KYC..."
    },
    eve_token_modal: {
      title: "The Future of EVE Token",
      description: "Your reward is more than just a token—it's a key to the future of finance.",
      exchange_listing_title: "Exchange Listing",
      exchange_listing_desc: "We're on a mission! Our roadmap includes listing EVE on major global exchanges, unlocking its true market value and providing you with worldwide liquidity.",
      blockchain_integration_title: "Blockchain Integration",
      blockchain_integration_desc: "EVE is destined for the blockchain. We are developing the technology to transition EVE into a fully decentralized asset, giving you self-custody and on-chain capabilities.",
      global_utility_title: "Global Utility",
      global_utility_desc: "Think bigger. EVE will become the lifeblood of our ecosystem, used for reduced fees, governance rights, and exclusive access to premium features and services.",
      button_text: "Sounds Exciting!"
    },
    us_stocks_guide: {
      tabs_intro: "US Stocks 101",
      tabs_stocks: "Stock Directory",
      tabs_charts: "Market Analytics",
      tabs_qa: "Q&A",
      hero_badge: "EVE FINANCE · US Stocks",
      hero_title: "Invest in America's Best Companies",
      hero_desc: "Trade tokenized shares of 20 top US stocks — Apple, NVIDIA, Tesla, OpenAI and more — with as little as $10, 24/7, from anywhere in the world.",
      stats_stocks: "Stocks Available",
      stats_market_cap: "Total Market Cap",
      stats_min_invest: "Min. Investment",
      stats_fee: "Trading Fee",
      what_is_stock_title: "What Is a Stock?",
      how_to_trade_title: "How to Trade US Stocks on EVE FINANCE",
      step1_title: "Deposit USDT or USD",
      step1_desc: "Fund your wallet using bank transfer or USDT (ERC20/TRC20/SOL). Min deposit $50.",
      step2_title: "Go to US Stocks",
      step2_desc: "Navigate to the US Stocks page from the sidebar. Browse real-time prices.",
      step3_title: "Choose a Stock & Order Type",
      step3_desc: "Select Market Order for instant execution, or Limit Order to set your target price.",
      step4_title: "Enter Amount & Confirm",
      step4_desc: "Enter how much USDT to spend. Review the fee and estimated shares. Confirm your trade.",
      step5_title: "Track Your Holdings",
      step5_desc: "Your shares appear in Holdings immediately. P&L updates in real-time with live prices.",
      market_order: "Market Order",
      market_order_desc: "Executes immediately at current market price. Best for quick entry.",
      limit_order: "Limit Order",
      limit_order_desc: "Set your target price. Funds frozen until price is reached or cancelled.",
      sectors_title: "What Sectors Can I Invest In?",
      diversification_tip: "Diversification Tip",
      diversification_desc: "Spreading investments across sectors reduces risk. When tech dips, consumer staples may hold steady.",
      risk_title: "Understanding Risk Levels",
      risk_disclaimer: "Past performance is not a guarantee of future results. All investments carry risk of loss.",
      search_placeholder: "Search by name, symbol, or industry…",
      sector_all: "All",
      sector_tech: "Technology",
      sector_ai: "AI",
      sector_crypto: "Crypto",
      stocks_count: "stocks",
      chart_market_cap: "Market Cap (Billion USD) — Top 10",
      chart_revenue: "Revenue Growth 2020–2023 ($B)",
      chart_quality: "Portfolio Quality Factors (US Tech)",
      chart_sector: "Sector Breakdown — Listed Stocks",
      table_title: "Mega-Cap Comparison (Top 6)",
      table_stock: "Stock",
      table_market_cap: "Market Cap",
      table_revenue: "Revenue",
      table_pe: "P/E",
      table_risk: "Risk",
      table_div: "Div.",
      faq_title: "Frequently Asked Questions",
      faq_subtitle: "Everything you need to know about US stock trading on EVE FINANCE",
      risk_disclosure_title: "Investment Risk Disclosure",
      risk_disclosure_desc: "Trading tokenized stocks involves significant risk, including the potential loss of your entire investment. Stock prices can be highly volatile and are affected by market conditions, company performance, economic factors, and geopolitical events. Past performance is not indicative of future results. This guide is for educational purposes only and does not constitute investment advice. Please invest only what you can afford to lose and consider consulting a licensed financial advisor."
    }
  },
  zh: {
    sidebar: {
      home: '主页',
      wallet: '钱包',
      trading: '交易',
      physical: '实物资产',
      loan: '借贷',
      staking: '质押',
      account: '账户',
      statement: '账单',
      guide: '指南',
      admin: '管理后台',
      security: '安全',
      security_desc: '您的资产受到机构级安全协议的保护。',
      bank_grade_security: '银行级安全',
    },
    login: {
      company_name: 'EVE FINANCE',
      company_tagline: '高端交易平台',
      future_of_trading: '贵金属交易的',
      precious_metals: '未来',
      trading: '',
      platform_description: '体验世界上最先进的贵金属平台。以机构级安全和闪电般快速的执行，交易黄金、白银、铂金和钯金。',
      bank_grade_security: '银行级安全与保险',
      instant_trading: '即时交易与实时定价',
      eve_rewards: 'EVE奖励 - 每1美元手续费获得100个EVE',
      account_access: '账户登录',
      login_description: '请登录以访问您的账户并管理您的KYC验证',
      login_with_google: '使用Google登录',
      secure_auth: '由Google提供的安全认证',
      military_encryption: '军事级加密保护',
      data_safe: '您的数据安全可靠'
    },
    home: {
      market_alert: '黄金 2025年 +50%',
      record_breaking: '破纪录的表现',
      golden_age: '黄金时代',
      is_here: '已经来临',
      surge_2025: '2025年，黄金价格飙升超过50%，震惊全球市场，重新点燃了世界各地投资者的热情。',
      inflation_fears: '随着通胀担忧、地缘政治紧张和法定货币不确定性的加剧，黄金再次证明了其永恒的价值。交易员、机构和散户投资者纷纷涌入，将价格推至历史新高。这次反弹使黄金成为年度表现最佳的资产。',
      safe_haven: '从避风港到利润引擎，黄金的复苏点亮了投资组合和新闻头条——而且这还没有结束。',
      golden_age_beginning: '黄金时代可能才刚刚开始。',
      start_trading: '开始交易黄金',
      view_prices: '查看实时价格',
      bank_grade_security: '银行级安全',
      instant_trading: '即时交易',
      live_market_data: '实时市场数据',
      market_leaders: '🏆 2025年市场领导者',
      metals_performance: '贵金属表现',
      witness_surge: '见证正在重塑全球投资组合的历史性飙升。这些不仅仅是金属——它们是金融安全的基石。',
      best_performer: '🔥 2025年最佳表现者',
      strong_rally: '📈 强劲反弹',
      rising_fast: '⚡ 快速上涨',
      steady_growth: '💎 稳定增长',
      gold_desc: '年度最佳表现者，前所未有的50%以上飙升，证明了其作为最终财富储存手段的持久价值。',
      silver_desc: '跟随黄金的势头，工业需求和货币吸引力推动了显著的增长。',
      platinum_desc: '受益于供应限制和汽车行业复苏，显示出投资者兴趣重燃。',
      palladium_desc: '科技行业需求和有限的供应继续支撑着高昂的价格水平。',
      zero_fees: '首个$10,000交易免手续费',
      revolutionary_platform: '⚡ 革命性平台',
      built_future: '为未来而建',
      advanced_platform: '体验有史以来最先进的贵金属平台。每个功能都为最大性能和安全性而设计。',
      instant_gold_trading: '即时黄金交易',
      execute_trades: '以实时市场价格在毫秒内执行交易。无延迟，无滑点——只有纯粹的速度。',
      asset_backed_lending: '资产支持借贷',
      unlock_liquidity: '无需出售即可释放流动性。以您的贵金属作抵押，以有竞争力的利率借款高达80%。',
      fort_knox_security: '诺克斯堡级安全',
      military_grade: '军事级保护，采用冷存储、保险和多重签名协议。',
      yield_generation: '收益生成',
      stake_metals: '质押您的金属以赚取被动收入。将您的投资组合变成利润引擎。',
      lightning_fast: '闪电般快速',
      fast_trading: '24/7交易，亚秒级执行。地球上最快的贵金属平台。',
      always_available: '始终可用',
      trade_anytime: '随时随地交易。我们的平台永不休眠，所以您的机会永不等待。',
      join_gold_rush: '加入淘金热',
      dont_miss: '不要错过这十年来最大的贵金属机会。立即开始交易。',
      active_traders: '50,000+ 活跃交易者',
      volume_traded: '28亿+ 美元交易额',
      uptime: '99.9%正常运行时间',
      eve_revolution: '🚀 EVE革命',
      introducing_eve: '介绍EVE代币',
      eve_subtitle: '世界首个贵金属交易奖励代币。每笔交易都能赚取EVE——您通往未来金融的门户。',
      earn_eve: '赚取EVE代币',
      earn_eve_desc: '每1美元交易费获得100个EVE代币。将您的交易活动转化为有价值的数字资产。',
      blockchain_ready: '区块链就绪',
      blockchain_desc: 'EVE为未来而设计。完整的区块链集成和自我托管功能即将推出。',
      global_exchange: '全球交易所上市',
      exchange_desc: '我们的路线图包括在全球主要交易所上市EVE，释放全球流动性和市场价值。',
      ecosystem_utility: '生态系统实用性',
      utility_desc: '使用EVE享受费用减免、治理投票以及独享高级功能和服务。',
      start_earning: '开始赚取EVE',
      learn_about_eve: '了解EVE',
      eve_stats_earned: '250万+ EVE已赚取',
      eve_stats_traders: '15,000+ EVE持有者',
      eve_stats_value: '每日增长'
    },
    wallet: {
      title: '投资组合钱包',
      subtitle: '管理您的贵金属和货币',
      deposit: '存款',
      kyc_required_tooltip: '请先完成KYC验证才能存款。',
      refresh: '刷新',
      total_portfolio_value: '总投资组合价值',
      change_24h: '24小时变化',
      active_assets: '活跃资产',
      asset_balances: '资产余额',
      live_prices: '实时价格',
      quick_actions: '快捷操作',
      transaction_history: '交易历史',
      requests_title: '存取款请求',
    },
    chatbot: {
      greeting_title: "你好！我是",
      greeting_subtitle: "你今天的个人助理。有什么可以帮您？",
      input_placeholder: "询问关于交易、贷款或KYC的问题..."
    },
    eve_token_modal: {
      title: "EVE代币的未来",
      description: "您的奖励不仅仅是一个代币——它是通往未来金融的关键。",
      exchange_listing_title: "交易所上市",
      exchange_listing_desc: "我们肩负使命！我们的路线图包括在全球主要交易所上市EVE，释放其真正的市场价值，并为您提供全球流动性。",
      blockchain_integration_title: "区块链整合",
      blockchain_integration_desc: "EVE注定要登上区块链。我们正在开发技术，将EVE转变为完全去中心化的资产，为您提供自我托管和链上功能。",
      global_utility_title: "全球实用性",
      global_utility_desc: "格局要大。EVE将成为我们生态系统的命脉，用于降低费用、治理权和独家访问高级功能。您的奖励仅仅是个开始。",
      button_text: "听起来很激动！"
    }
  },
  id: {
    sidebar: {
      home: 'Beranda',
      wallet: 'Dompet',
      trading: 'Perdagangan',
      physical: 'Fisik',
      loan: 'Pinjaman',
      staking: 'Staking',
      account: 'Akun',
      statement: 'Laporan',
      guide: 'Panduan',
      admin: 'Admin',
      security: 'Keamanan',
      security_desc: 'Aset Anda dilindungi dengan protokol keamanan tingkat institusional.',
      bank_grade_security: 'Keamanan Tingkat Bank',
    },
    login: {
      company_name: 'EVE FINANCE',
      company_tagline: 'Platform Premium',
      future_of_trading: 'Masa Depan',
      precious_metals: 'Perdagangan Logam Mulia',
      trading: '',
      platform_description: 'Rasakan platform logam mulia paling canggih di dunia. Perdagangkan emas, perak, platinum, dan paladium dengan keamanan tingkat institusional dan eksekusi secepat kilat.',
      bank_grade_security: 'Keamanan & Asuransi Tingkat Bank',
      instant_trading: 'Perdagangan Instan & Harga Real-Time',
      eve_rewards: 'EVE Rewards - Dapatkan 100 EVE per $1 Biaya',
      account_access: 'Akses Akun',
      login_description: 'Silakan masuk untuk mengakses akun Anda dan mengelola verifikasi KYC',
      login_with_google: 'Masuk dengan Google',
      secure_auth: 'Autentikasi aman didukung oleh Google',
      military_encryption: 'Dilindungi dengan enkripsi tingkat militer',
      data_safe: 'Data Anda aman bersama kami'
    },
    home: {
      market_alert: 'EMAS +50% PADA 2025',
      record_breaking: 'Performa Memecahkan Rekor',
      golden_age: 'Zaman Keemasan',
      is_here: 'Telah Tiba',
      surge_2025: 'Pada tahun 2025, EMAS melonjak lebih dari 50%, mengejutkan pasar global dan menghidupkan kembali kegembiraan investor di seluruh dunia.',
      inflation_fears: 'Seiring meningkatnya kekhawatiran inflasi, ketegangan geopolitik, dan ketidakpastian fiat, emas sekali lagi membuktikan nilai abadinya. Para pedagang, institusi, dan investor ritel bergegas masuk, mendorong harga ke rekor tertinggi. Reli tersebut mengubah emas menjadi aset dengan kinerja terbaik tahun ini.',
      safe_haven: 'Dari tempat berlindung yang aman menjadi mesin keuntungan, kebangkitan emas menerangi portofolio dan berita utama — dan ini belum berakhir.',
      golden_age_beginning: 'Zaman keemasan mungkin baru saja dimulai.',
      start_trading: 'Mulai Berdagang Emas',
      view_prices: 'Lihat Harga Langsung',
      bank_grade_security: 'Keamanan Tingkat Bank',
      instant_trading: 'Perdagangan Instan',
      live_market_data: 'Data Pasar Langsung',
      market_leaders: '🏆 Pemimpin Pasar 2025',
      metals_performance: 'Kinerja Logam Mulia',
      witness_surge: 'Saksikan lonjakan bersejarah yang membentuk kembali portofolio investasi di seluruh dunia. Ini bukan hanya logam — ini adalah fondasi keamanan finansial.',
      best_performer: '🔥 Performer Terbaik 2025',
      strong_rally: '📈 Reli Kuat',
      rising_fast: '⚡ Naik Cepat',
      steady_growth: '💎 Pertumbuhan Stabil',
      gold_desc: 'Performer teratas tahun ini dengan lonjakan 50+ yang belum pernah terjadi sebelumnya, membuktikan nilai abadinya sebagai penyimpan kekayaan utama.',
      silver_desc: 'Mengikuti momentum emas dengan permintaan industri dan daya tarik moneter yang mendorong keuntungan signifikan.',
      platinum_desc: 'Mendapat manfaat dari kendala pasokan dan pemulihan otomotif, menunjukkan minat investor yang diperbarui.',
      palladium_desc: 'Permintaan sektor teknologi dan pasokan terbatas terus mendukung tingkat harga yang tinggi.',
      zero_fees: 'Berdagang semua logam dengan biaya nol untuk $10.000 pertama Anda',
      revolutionary_platform: '⚡ Platform Revolusioner',
      built_future: 'Dibangun untuk Masa Depan',
      advanced_platform: 'Alami platform logam mulia paling canggih yang pernah dibuat. Setiap fitur dirancang untuk kinerja dan keamanan maksimum.',
      instant_gold_trading: 'Perdagangan Emas Instan',
      execute_trades: 'Eksekusi perdagangan dalam milidetik dengan harga pasar langsung. Tanpa penundaan, tanpa selip — hanya kecepatan murni.',
      asset_backed_lending: 'Pinjaman Beragun Aset',
      unlock_liquidity: 'Buka likuiditas tanpa menjual. Pinjam hingga 80% dari logam mulia Anda dengan suku bunga kompetitif.',
      fort_knox_security: 'Keamanan Fort Knox',
      military_grade: 'Perlindungan tingkat militer dengan penyimpanan dingin, asuransi, dan protokol multi-tanda tangan.',
      yield_generation: 'Penghasilan Hasil',
      stake_metals: 'Pertaruhkan logam Anda dan dapatkan penghasilan pasif. Ubah portofolio Anda menjadi mesin keuntungan.',
      lightning_fast: 'Secepat Kilat',
      fast_trading: 'Perdagangan 24/7 dengan eksekusi sub-detik. Platform logam mulia tercepat di dunia.',
      always_available: 'Selalu Tersedia',
      trade_anytime: 'Berdagang kapan saja, di mana saja. Platform kami tidak pernah tidur, jadi peluang Anda tidak pernah menunggu.',
      join_gold_rush: 'Ikuti Demam Emas',
      dont_miss: 'Jangan lewatkan peluang logam mulia terbesar dekade ini. Mulai berdagang hari ini.',
      active_traders: '50.000+ Pedagang Aktif',
      volume_traded: '$2,8M+ Volume Diperdagangkan',
      uptime: '99.9% Uptime',
      eve_revolution: '🚀 Revolusi EVE',
      introducing_eve: 'Memperkenalkan Token EVE',
      eve_subtitle: 'Token reward trading logam mulia pertama di dunia. Setiap perdagangan menghasilkan EVE—pintu gerbang Anda ke masa depan keuangan.',
      earn_eve: 'Dapatkan Token EVE',
      earn_eve_desc: 'Dapatkan 100 token EVE untuk setiap $1 biaya trading. Ubah aktivitas trading Anda menjadi aset digital berharga.',
      blockchain_ready: 'Siap Blockchain',
      blockchain_desc: 'EVE dirancang untuk masa depan. Integrasi blockchain penuh dan kemampuan self-custody segera hadir.',
      global_exchange: 'Listing Exchange Global',
      exchange_desc: 'Roadmap kami mencakup listing EVE di exchange besar dunia, membuka likuiditas global dan nilai pasar.',
      ecosystem_utility: 'Utilitas Ekosistem',
      utility_desc: 'Gunakan EVE untuk pengurangan biaya, voting governance, dan akses eksklusif ke fitur dan layanan premium.',
      start_earning: 'Mulai Dapatkan EVE',
      learn_about_eve: 'Pelajari Tentang EVE',
      eve_stats_earned: '2.5M+ EVE Diperoleh',
      eve_stats_traders: '15.000+ Pemegang EVE',
      eve_stats_value: 'Tumbuh Setiap Hari'
    },
    wallet: {
      title: 'Dompet Portofolio',
      subtitle: 'Kelola logam mulia dan mata uang Anda',
      deposit: 'Deposit',
      kyc_required_tooltip: 'Harap selesaikan KYC untuk melakukan deposit dana.',
      refresh: 'Segarkan',
      total_portfolio_value: 'Total Nilai Portofolio',
      change_24h: 'Perubahan 24 jam',
      active_assets: 'Aset Aktif',
      asset_balances: 'Saldo Aset',
      live_prices: 'Harga Langsung',
      quick_actions: 'Tindakan Cepat',
      transaction_history: 'Riwayat Transaksi',
      requests_title: 'Permintaan Deposit/Penarikan',
    },
    chatbot: {
      greeting_title: "Halo! Saya",
      greeting_subtitle: "Asisten pribadi Anda untuk hari ini. Ada yang bisa saya bantu?",
      input_placeholder: "Tanya tentang perdagangan, pinjaman, atau KYC..."
    },
    eve_token_modal: {
      title: "Masa Depan Token EVE",
      description: "Hadiah Anda lebih dari sekadar token—ini adalah kunci menuju masa depan keuangan.",
      exchange_listing_title: "Listing di Bursa",
      exchange_listing_desc: "Kami sedang dalam misi! Peta jalan kami mencakup pencatatan EVE di bursa global utama, membuka nilai pasar sebenarnya dan memberi Anda likuiditas di seluruh dunia.",
      blockchain_integration_title: "Integrasi Blockchain",
      blockchain_integration_desc: "EVE ditakdirkan untuk blockchain. Kami sedang mengembangkan teknologi untuk mentransisikan EVE menjadi aset yang sepenuhnya terdesentralisasi, memberi Anda kemampuan penyimpanan mandiri dan on-chain.",
      global_utility_title: "Utilitas Global",
      global_utility_desc: "Berpikirlah lebih besar. EVE akan menjadi sumber kehidupan ekosistem kami, digunakan untuk biaya yang lebih rendah, hak tata kelola, dan akses eksklusif ke fitur-fitur premium. Hadiah Anda hanyalah permulaan.",
      button_text: "Terdengar Menarik!"
    },
    us_stocks_guide: {
      tabs_intro: "Saham AS 101",
      tabs_stocks: "Direktori Saham",
      tabs_charts: "Analisis Pasar",
      tabs_qa: "Tanya Jawab",
      hero_badge: "EVE FINANCE · Saham AS",
      hero_title: "Investasi di Perusahaan Terbaik Amerika",
      hero_desc: "Perdagangkan 20 saham AS teratas yang di-tokenisasi — Apple, NVIDIA, Tesla, OpenAI, dan lainnya — mulai dari $10, 24/7, dari mana saja di dunia.",
      stats_stocks: "Saham Tersedia",
      stats_market_cap: "Total Kapitalisasi Pasar",
      stats_min_invest: "Investasi Minimum",
      stats_fee: "Biaya Trading",
      what_is_stock_title: "Apa Itu Saham?",
      how_to_trade_title: "Cara Trading Saham AS di EVE FINANCE",
      step1_title: "Setor USDT atau USD",
      step1_desc: "Danai dompet Anda menggunakan transfer bank atau USDT (ERC20/TRC20/SOL). Minimum deposit $50.",
      step2_title: "Buka Halaman Saham AS",
      step2_desc: "Arahkan ke halaman Saham AS dari sidebar. Jelajahi harga real-time.",
      step3_title: "Pilih Saham & Jenis Order",
      step3_desc: "Pilih Market Order untuk eksekusi instan, atau Limit Order untuk menetapkan harga target Anda.",
      step4_title: "Masukkan Jumlah & Konfirmasi",
      step4_desc: "Masukkan berapa banyak USDT yang akan dibelanjakan. Tinjau biaya dan estimasi saham. Konfirmasi trading Anda.",
      step5_title: "Lacak Kepemilikan Anda",
      step5_desc: "Saham Anda muncul di Kepemilikan segera. P&L diperbarui secara real-time dengan harga langsung.",
      market_order: "Market Order",
      market_order_desc: "Dieksekusi segera pada harga pasar saat ini. Terbaik untuk masuk cepat.",
      limit_order: "Limit Order",
      limit_order_desc: "Tetapkan harga target Anda. Dana dibekukan sampai harga tercapai atau dibatalkan.",
      sectors_title: "Sektor Apa yang Bisa Saya Investasikan?",
      diversification_tip: "Tips Diversifikasi",
      diversification_desc: "Menyebarkan investasi di berbagai sektor mengurangi risiko. Ketika teknologi turun, saham konsumen mungkin tetap stabil.",
      risk_title: "Memahami Tingkat Risiko",
      risk_disclaimer: "Kinerja masa lalu bukan jaminan hasil masa depan. Semua investasi membawa risiko kerugian.",
      search_placeholder: "Cari berdasarkan nama, simbol, atau industri…",
      sector_all: "Semua",
      sector_tech: "Teknologi",
      sector_ai: "AI",
      sector_crypto: "Kripto",
      stocks_count: "saham",
      chart_market_cap: "Kapitalisasi Pasar (Miliar USD) — Top 10",
      chart_revenue: "Pertumbuhan Pendapatan 2020–2023 ($B)",
      chart_quality: "Faktor Kualitas Portofolio (Teknologi AS)",
      chart_sector: "Rincian Sektor — Saham Tercatat",
      table_title: "Perbandingan Mega-Cap (Top 6)",
      table_stock: "Saham",
      table_market_cap: "Kapitalisasi Pasar",
      table_revenue: "Pendapatan",
      table_pe: "P/E",
      table_risk: "Risiko",
      table_div: "Dividen",
      faq_title: "Pertanyaan yang Sering Diajukan",
      faq_subtitle: "Semua yang perlu Anda ketahui tentang trading saham AS di EVE FINANCE",
      risk_disclosure_title: "Pengungkapan Risiko Investasi",
      risk_disclosure_desc: "Trading saham yang di-tokenisasi melibatkan risiko signifikan, termasuk potensi kehilangan seluruh investasi Anda. Harga saham bisa sangat volatil dan dipengaruhi oleh kondisi pasar, kinerja perusahaan, faktor ekonomi, dan peristiwa geopolitik. Kinerja masa lalu tidak menunjukkan hasil masa depan. Panduan ini hanya untuk tujuan pendidikan dan bukan merupakan saran investasi. Harap investasikan hanya apa yang Anda mampu untuk kehilangan dan pertimbangkan untuk berkonsultasi dengan penasihat keuangan berlisensi."
    }
  },
  vi: {
    sidebar: {
      home: 'Trang chủ',
      wallet: 'Ví',
      trading: 'Giao dịch',
      physical: 'Vật chất',
      loan: 'Khoản vay',
      staking: 'Staking',
      account: 'Tài khoản',
      statement: 'Sao kê',
      guide: 'Hướng dẫn',
      admin: 'Quản trị viên',
      security: 'Bảo mật',
      security_desc: 'Tài sản của bạn được bảo vệ bằng các giao thức bảo mật cấp tổ chức.',
      bank_grade_security: 'Bảo mật cấp ngân hàng',
    },
    login: {
      company_name: 'EVE FINANCE',
      company_tagline: 'Nền tảng cao cấp',
      future_of_trading: 'Tương lai của',
      precious_metals: 'Giao dịch Kim loại Quý',
      trading: '',
      platform_description: 'Trải nghiệm nền tảng kim loại quý tiên tiến nhất thế giới. Giao dịch vàng, bạc, bạch kim và palladium với bảo mật cấp tổ chức và thực thi nhanh như chớp.',
      bank_grade_security: 'Bảo mật & Bảo hiểm cấp Ngân hàng',
      instant_trading: 'Giao dịch Tức thời & Định giá Thời gian thực',
      eve_rewards: 'Phần thưởng EVE - Nhận 100 EVE cho mỗi $1 phí',
      account_access: 'Truy cập Tài khoản',
      login_description: 'Vui lòng đăng nhập để truy cập tài khoản và quản lý xác minh KYC của bạn',
      login_with_google: 'Đăng nhập bằng Google',
      secure_auth: 'Xác thực an toàn được hỗ trợ bởi Google',
      military_encryption: 'Được bảo vệ bằng mã hóa cấp quân sự',
      data_safe: 'Dữ liệu của bạn an toàn với chúng tôi'
    },
    home: {
      market_alert: 'VÀNG +50% VÀO NĂM 2025',
      record_breaking: 'Hiệu suất Phá kỷ lục',
      golden_age: 'Thời đại Hoàng kim',
      is_here: 'Đã đến',
      surge_2025: 'Vào năm 2025, VÀNG đã tăng hơn 50%, gây chấn động thị trường toàn cầu và khơi lại sự phấn khích của nhà đầu tư trên toàn thế giới.',
      inflation_fears: 'Khi nỗi lo lạm phát, căng thẳng địa chính trị và sự không chắc chắn của tiền tệ fiat tăng lên, vàng một lần nữa chứng tỏ giá trị vượt thời gian của mình. Các nhà giao dịch, tổ chức và nhà đầu tư bán lẻ đã đổ xô vào, đẩy giá lên mức cao kỷ lục. Đợt tăng giá đã biến vàng thành tài sản có hiệu suất tốt nhất trong năm.',
      safe_haven: 'Từ một nơi trú ẩn an toàn đến một động cơ lợi nhuận, sự trỗi dậy của vàng đã thắp sáng các danh mục đầu tư và các tiêu đề tin tức — và nó vẫn chưa kết thúc.',
      golden_age_beginning: 'Thời đại hoàng kim có thể mới chỉ bắt đầu.',
      start_trading: 'Bắt đầu Giao dịch Vàng',
      view_prices: 'Xem Giá Trực tiếp',
      bank_grade_security: 'Bảo mật Cấp ngân hàng',
      instant_trading: 'Giao dịch Tức thì',
      live_market_data: 'Dữ liệu Thị trường Trực tiếp',
      market_leaders: '🏆 Các nhà Lãnh đạo Thị trường 2025',
      metals_performance: 'Hiệu suất Kim loại Quý',
      witness_surge: 'Chứng kiến sự gia tăng lịch sử đang định hình lại các danh mục đầu tư trên toàn thế giới. Đây không chỉ là kim loại — chúng là nền tảng của an ninh tài chính.',
      best_performer: '🔥 Người biểu diễn tốt nhất năm 2025',
      strong_rally: '📈 Đợt tăng giá mạnh mẽ',
      rising_fast: '⚡ Tăng nhanh',
      steady_growth: '💎 Tăng trưởng ổn định',
      gold_desc: 'Người biểu diễn hàng đầu của năm với sự gia tăng chưa từng có hơn 50, chứng tỏ giá trị lâu dài của nó như một kho lưu trữ của cải cuối cùng.',
      silver_desc: 'Theo đà của vàng với nhu cầu công nghiệp và sức hấp dẫn tiền tệ thúc đẩy lợi nhuận đáng kể.',
      platinum_desc: 'Hưởng lợi từ những hạn chế về nguồn cung và sự phục hồi của ngành ô tô, cho thấy sự quan tâm mới của nhà đầu tư.',
      palladium_desc: 'Nhu cầu của ngành công nghệ và nguồn cung hạn chế tiếp tục hỗ trợ mức giá cao.',
      zero_fees: 'Giao dịch tất cả kim loại với phí bằng không cho 10.000 đô la đầu tiên của bạn',
      revolutionary_platform: '⚡ Nền tảng Cách mạng',
      built_future: 'Được xây dựng cho Tương lai',
      advanced_platform: 'Trải nghiệm nền tảng kim loại quý tiên tiến nhất từng được tạo ra. Mọi tính năng được thiết kế để có hiệu suất và bảo mật tối đa.',
      instant_gold_trading: 'Giao dịch Vàng Tức thì',
      execute_trades: 'Thực hiện giao dịch trong mili giây với giá thị trường trực tiếp. Không có độ trễ, không có trượt giá — chỉ có tốc độ thuần túy.',
      asset_backed_lending: 'Cho vay Có tài sản đảm bảo',
      unlock_liquidity: 'Mở khóa thanh khoản mà không cần bán. Vay tới 80% so với kim loại quý của bạn với lãi suất cạnh tranh.',
      fort_knox_security: 'Bảo mật Fort Knox',
      military_grade: 'Bảo vệ cấp quân sự với lưu trữ lạnh, bảo hiểm và giao thức đa chữ ký.',
      yield_generation: 'Tạo ra Lợi nhuận',
      stake_metals: 'Đặt cược kim loại của bạn và kiếm thu nhập thụ động. Biến danh mục đầu tư của bạn thành một động cơ lợi nhuận.',
      lightning_fast: 'Nhanh như chớp',
      fast_trading: 'Giao dịch 24/7 với thực thi dưới giây. Nền tảng kim loại quý nhanh nhất trên trái đất.',
      always_available: 'Luôn có sẵn',
      trade_anytime: 'Giao dịch mọi lúc, mọi nơi. Nền tảng của chúng tôi không bao giờ ngủ, vì vậy cơ hội của bạn không bao giờ phải chờ đợi.',
      join_gold_rush: 'Tham gia Cơn sốt Vàng',
      dont_miss: 'Đừng bỏ lỡ cơ hội kim loại quý lớn nhất của thập kỷ. Bắt đầu giao dịch ngay hôm nay.',
      active_traders: '50.000+ Nhà giao dịch đang hoạt động',
      volume_traded: 'Khối lượng giao dịch hơn 2,8 tỷ đô la',
      uptime: '99.9% Thời gian hoạt động',
      eve_revolution: '🚀 Cuộc Cách Mạng EVE',
      introducing_eve: 'Giới thiệu Token EVE',
      eve_subtitle: 'Token thưởng giao dịch kim loại quý đầu tiên trên thế giới. Mỗi giao dịch đều kiếm được EVE—cổng vào tương lai tài chính của bạn.',
      earn_eve: 'Kiếm Token EVE',
      earn_eve_desc: 'Nhận 100 token EVE cho mỗi $1 phí giao dịch. Biến hoạt động giao dịch của bạn thành tài sản số có giá trị.',
      blockchain_ready: 'Sẵn sàng Blockchain',
      blockchain_desc: 'EVE được thiết kế cho tương lai. Tích hợp blockchain đầy đủ và khả năng tự quản lý sắp ra mắt.',
      global_exchange: 'Niêm yết Sàn Giao dịch Toàn cầu',
      exchange_desc: 'Lộ trình của chúng tôi bao gồm niêm yết EVE trên các sàn giao dịch lớn toàn cầu, mở khóa tính thanh khoản và giá trị thị trường.',
      ecosystem_utility: 'Tiện ích Hệ sinh thái',
      utility_desc: 'Sử dụng EVE để giảm phí, bỏ phiếu quản trị và truy cập độc quyền vào các tính năng và dịch vụ cao cấp.',
      start_earning: 'Bắt đầu Kiếm EVE',
      learn_about_eve: 'Tìm hiểu về EVE',
      eve_stats_earned: '2.5M+ EVE Đã kiếm',
      eve_stats_traders: '15,000+ Người nắm giữ EVE',
      eve_stats_value: 'Tăng trưởng Hàng ngày'
    },
    wallet: {
      title: 'Ví danh mục đầu tư',
      subtitle: 'Quản lý kim loại quý và tiền tệ của bạn',
      deposit: 'Nạp tiền',
      kyc_required_tooltip: 'Vui lòng hoàn thành KYC để nạp tiền.',
      refresh: 'Làm mới',
      total_portfolio_value: 'Tổng giá trị danh mục đầu tư',
      change_24h: 'Thay đổi 24 giờ',
      active_assets: 'Tài sản đang hoạt động',
      asset_balances: 'Số dư tài sản',
      live_prices: 'Giá trực tiếp',
      quick_actions: 'Hành động nhanh',
      transaction_history: 'Lịch sử giao dịch',
      requests_title: 'Yêu cầu Nạp/Rút tiền',
    },
    chatbot: {
      greeting_title: "Xin chào! Tôi là",
      greeting_subtitle: "Trợ lý cá nhân của bạn hôm nay. Tôi có thể giúp gì cho bạn?",
      input_placeholder: "Hỏi về giao dịch, cho vay, hoặc KYC..."
    },
    eve_token_modal: {
      title: "Tương lai của Token EVE",
      description: "Phần thưởng của bạn không chỉ là một token—đó là chìa khóa cho tương lai của tài chính.",
      exchange_listing_title: "Niêm yết trên Sàn giao dịch",
      exchange_listing_desc: "Chúng tôi đang thực hiện một sứ mệnh! Lộ trình của chúng tôi bao gồm việc niêm yết EVE trên các sàn giao dịch lớn toàn cầu, mở khóa giá trị thị trường thực sự của nó và cung cấp cho bạn thanh khoản trên toàn thế giới.",
      blockchain_integration_title: "Tích hợp Blockchain",
      blockchain_integration_desc: "EVE được định sẵn cho blockchain. Chúng tôi đang phát triển công nghệ để chuyển đổi EVE thành một tài sản hoàn toàn phi tập trung, mang lại cho bạn khả năng tự quản lý và các tính năng trên chuỗi.",
      global_utility_title: "Tiện ích Toàn cầu",
      global_utility_desc: "Hãy nghĩ lớn hơn. EVE sẽ trở thành huyết mạch của hệ sinh thái của chúng tôi, được sử dụng để giảm phí, quyền quản trị và quyền truy cập độc quyền vào các tính năng cao cấp. Phần thưởng của bạn chỉ là bước khởi đầu.",
      button_text: "Nghe có vẻ hấp dẫn!"
    },
    us_stocks_guide: {
      tabs_intro: "Chứng khoán Mỹ 101",
      tabs_stocks: "Danh mục Chứng khoán",
      tabs_charts: "Phân tích Thị trường",
      tabs_qa: "Hỏi & Đáp",
      hero_badge: "EVE FINANCE · Chứng khoán Mỹ",
      hero_title: "Đầu tư vào Các Công ty Tốt nhất Nước Mỹ",
      hero_desc: "Giao dịch 20 cổ phiếu Mỹ hàng đầu được token hóa — Apple, NVIDIA, Tesla, OpenAI và nhiều hơn nữa — chỉ từ $10, 24/7, từ bất kỳ đâu trên thế giới.",
      stats_stocks: "Chứng khoán Khả dụng",
      stats_market_cap: "Tổng Vốn hóa Thị trường",
      stats_min_invest: "Đầu tư Tối thiểu",
      stats_fee: "Phí Giao dịch",
      what_is_stock_title: "Cổ phiếu Là gì?",
      how_to_trade_title: "Cách Giao dịch Chứng khoán Mỹ trên EVE FINANCE",
      step1_title: "Nạp USDT hoặc USD",
      step1_desc: "Nạp tiền vào ví của bạn bằng chuyển khoản ngân hàng hoặc USDT (ERC20/TRC20/SOL). Tối thiểu nạp $50.",
      step2_title: "Truy cập Chứng khoán Mỹ",
      step2_desc: "Điều hướng đến trang Chứng khoán Mỹ từ thanh bên. Duyệt qua giá thời gian thực.",
      step3_title: "Chọn Cổ phiếu & Loại Lệnh",
      step3_desc: "Chọn Lệnh Thị trường để thực hiện ngay lập tức, hoặc Lệnh Giới hạn để đặt giá mục tiêu của bạn.",
      step4_title: "Nhập Số tiền & Xác nhận",
      step4_desc: "Nhập số USDT muốn chi tiêu. Xem lại phí và số cổ phiếu ước tính. Xác nhận giao dịch của bạn.",
      step5_title: "Theo dõi Danh mục",
      step5_desc: "Cổ phiếu của bạn xuất hiện trong Danh mục ngay lập tức. Lãi/Lỗ được cập nhật thời gian thực với giá trực tiếp.",
      market_order: "Lệnh Thị trường",
      market_order_desc: "Thực hiện ngay lập tức theo giá thị trường hiện tại. Tốt nhất cho việc vào lệnh nhanh.",
      limit_order: "Lệnh Giới hạn",
      limit_order_desc: "Đặt giá mục tiêu của bạn. Tiền bị đóng băng cho đến khi giá đạt được hoặc hủy.",
      sectors_title: "Tôi Có Thể Đầu Tư Vào Những Ngành Nào?",
      diversification_tip: "Mẹo Đa dạng hóa",
      diversification_desc: "Phân bổ đầu tư qua các ngành giảm thiểu rủi ro. Khi công nghệ giảm, hàng tiêu dùng có thể giữ vững.",
      risk_title: "Hiểu Mức Độ Rủi ro",
      risk_disclaimer: "Hiệu suất trong quá khứ không đảm bảo kết quả tương lai. Tất cả đầu tư đều mang rủi ro thua lỗ.",
      search_placeholder: "Tìm theo tên, ký hiệu, hoặc ngành…",
      sector_all: "Tất cả",
      sector_tech: "Công nghệ",
      sector_ai: "AI",
      sector_crypto: "Tiền mã hóa",
      stocks_count: "cổ phiếu",
      chart_market_cap: "Vốn hóa Thị trường (Tỷ USD) — Top 10",
      chart_revenue: "Tăng trưởng Doanh thu 2020–2023 ($B)",
      chart_quality: "Yếu tố Chất lượng Danh mục (Công nghệ Mỹ)",
      chart_sector: "Phân bổ Ngành — Cổ phiếu Niêm yết",
      table_title: "So sánh Mega-Cap (Top 6)",
      table_stock: "Cổ phiếu",
      table_market_cap: "Vốn hóa Thị trường",
      table_revenue: "Doanh thu",
      table_pe: "P/E",
      table_risk: "Rủi ro",
      table_div: "Cổ tức",
      faq_title: "Câu hỏi Thường gặp",
      faq_subtitle: "Mọi điều bạn cần biết về giao dịch chứng khoán Mỹ trên EVE FINANCE",
      risk_disclosure_title: "Tiết lộ Rủi ro Đầu tư",
      risk_disclosure_desc: "Giao dịch cổ phiếu token hóa liên quan đến rủi ro đáng kể, bao gồm khả năng mất toàn bộ khoản đầu tư của bạn. Giá cổ phiếu có thể biến động cao và bị ảnh hưởng bởi điều kiện thị trường, hiệu suất công ty, yếu tố kinh tế và sự kiện địa chính trị. Hiệu suất trong quá khứ không phản ánh kết quả tương lai. Hướng dẫn này chỉ dành cho mục đích giáo dục và không cấu thành lời khuyên đầu tư. Vui lòng chỉ đầu tư số tiền bạn có thể chấp nhận mất và cân nhắc tham khảo ý kiến cố vấn tài chính được cấp phép."
    }
  },
  th: {
    sidebar: {
      home: 'หน้าแรก',
      wallet: 'กระเป๋าเงิน',
      trading: 'การซื้อขาย',
      physical: 'สินทรัพย์กายภาพ',
      loan: 'สินเชื่อ',
      staking: 'การเดิมพัน',
      account: 'บัญชี',
      statement: 'ใบแจ้งยอด',
      guide: 'คู่มือ',
      admin: 'ผู้ดูแลระบบ',
      security: 'ความปลอดภัย',
      security_desc: 'สินทรัพย์ของคุณได้รับการคุ้มครองด้วยโปรโตคอลความปลอดภัยระดับสถาบัน',
      bank_grade_security: 'ความปลอดภัยระดับธนาคาร',
    },
    login: {
      company_name: 'EVE FINANCE',
      company_tagline: 'แพลตฟอร์มพรีเมียม',
      future_of_trading: 'อนาคตของ',
      precious_metals: 'การซื้อขายโลหะมีค่า',
      trading: '',
      platform_description: 'สัมผัสกับแพลตฟอร์มโลหะมีค่าที่ทันสมัยที่สุดในโลก ซื้อขายทองคำ เงิน แพลตตินัม และแพลเลเดียม ด้วยความปลอดภัยระดับสถาบันและการดำเนินการที่รวดเร็วปานสายฟ้า',
      bank_grade_security: 'ความปลอดภัยและการประกันระดับธนาคาร',
      instant_trading: 'การซื้อขายทันทีและการกำหนดราคาแบบเรียลไทม์',
      eve_rewards: 'รางวัล EVE - รับ 100 EVE ต่อค่าธรรมเนียม $1',
      account_access: 'เข้าสู่บัญชี',
      login_description: 'โปรดเข้าสู่ระบบเพื่อเข้าถึงบัญชีของคุณและจัดการการยืนยัน KYC',
      login_with_google: 'เข้าสู่ระบบด้วย Google',
      secure_auth: 'การยืนยันตัวตนที่ปลอดภัยโดย Google',
      military_encryption: 'ได้รับการปกป้องด้วยการเข้ารหัสระดับทหาร',
      data_safe: 'ข้อมูลของคุณปลอดภัยกับเรา'
    },
    home: {
      market_alert: 'ทองคำ +50% ในปี 2025',
      record_breaking: 'ผลการดำเนินงานทำลายสถิติ',
      golden_age: 'ยุคทอง',
      is_here: 'อยู่ที่นี่แล้ว',
      surge_2025: 'ในปี 2025 ทองคำพุ่งขึ้นกว่า 50% ทำให้ตลาดโลกตกตะลึงและจุดประกายความตื่นเต้นของนักลงทุนทั่วโลกอีกครั้ง',
      inflation_fears: 'ในขณะที่ความกลัวเงินเฟ้อ ความตึงเครียดทางภูมิรัฐศาสตร์ และความไม่แน่นอนของเงินเฟียตทวีความรุนแรงขึ้น ทองคำได้พิสูจน์คุณค่าอมตะของมันอีกครั้ง เทรดเดอร์ สถาบัน และนักลงทุนรายย่อยต่างรีบเข้ามา ทำให้ราคาสูงเป็นประวัติการณ์ การพุ่งขึ้นของราคาทำให้ทองคำกลายเป็นสินทรัพย์ที่ให้ผลตอบแทนดีที่สุดแห่งปี',
      safe_haven: 'จากที่หลบภัยสู่เครื่องมือทำกำไร การฟื้นตัวของทองคำทำให้พอร์ตการลงทุนและหัวข้อข่าวสว่างไสว — และยังไม่จบเพียงเท่านี้',
      golden_age_beginning: 'ยุคทองอาจเพิ่งเริ่มต้น',
      start_trading: 'เริ่มซื้อขายทองคำ',
      view_prices: 'ดูราคาสด',
      bank_grade_security: 'ความปลอดภัยระดับธนาคาร',
      instant_trading: 'การซื้อขายทันที',
      live_market_data: 'ข้อมูลตลาดสด',
      market_leaders: '🏆 ผู้นำตลาดปี 2025',
      metals_performance: 'ประสิทธิภาพของโลหะมีค่า',
      witness_surge: 'ร่วมเป็นสักขีพยานในการพุ่งขึ้นครั้งประวัติศาสตร์ที่กำลังปรับเปลี่ยนพอร์ตการลงทุนทั่วโลก นี่ไม่ใช่แค่โลหะ — แต่เป็นรากฐานของความมั่นคงทางการเงิน',
      best_performer: '🔥 ผู้ทำผลงานดีที่สุดปี 2025',
      strong_rally: '📈 การฟื้นตัวที่แข็งแกร่ง',
      rising_fast: '⚡ เพิ่มขึ้นอย่างรวดเร็ว',
      steady_growth: '💎 การเติบโตที่มั่นคง',
      gold_desc: 'ผู้ทำผลงานดีที่สุดแห่งปีด้วยการพุ่งขึ้นกว่า 50% อย่างไม่เคยปรากฏมาก่อน พิสูจน์คุณค่าที่ยั่งยืนในฐานะแหล่งเก็บความมั่งคั่งขั้นสูงสุด',
      silver_desc: 'ตามโมเมนตัมของทองคำด้วยอุปสงค์ทางอุตสาหกรรมและเสน่ห์ทางการเงินที่ผลักดันให้เกิดผลกำไรอย่างมีนัยสำคัญ',
      platinum_desc: 'ได้รับประโยชน์จากข้อจำกัดด้านอุปทานและการฟื้นตัวของยานยนต์ แสดงให้เห็นถึงความสนใจของนักลงทุนที่กลับมาอีกครั้ง',
      palladium_desc: 'ความต้องการของภาคเทคโนโลยีและอุปทานที่จำกัดยังคงสนับสนุนระดับราคาสูง',
      zero_fees: 'ซื้อขายโลหะทุกชนิดโดยไม่มีค่าธรรมเนียมสำหรับ $10,000 แรกของคุณ',
      revolutionary_platform: '⚡ แพลตฟอร์มปฏิวัติวงการ',
      built_future: 'สร้างขึ้นเพื่ออนาคต',
      advanced_platform: 'สัมผัสกับแพลตฟอร์มโลหะมีค่าที่ทันสมัยที่สุดเท่าที่เคยมีมา ทุกฟีเจอร์ออกแบบมาเพื่อประสิทธิภาพและความปลอดภัยสูงสุด',
      instant_gold_trading: 'การซื้อขายทองคำทันที',
      execute_trades: 'ดำเนินการซื้อขายในหน่วยมิลลิวินาทีด้วยราคาตลาดสด ไม่มีความล่าช้า ไม่มีการคลาดเคลื่อน — มีแต่ความเร็วล้วนๆ',
      asset_backed_lending: 'การให้กู้ยืมโดยมีสินทรัพย์ค้ำประกัน',
      unlock_liquidity: 'ปลดล็อกสภาพคล่องโดยไม่ต้องขาย กู้ยืมสูงถึง 80% จากโลหะมีค่าของคุณในอัตราที่แข่งขันได้',
      fort_knox_security: 'ความปลอดภัยระดับฟอร์ต น็อกซ์',
      military_grade: 'การป้องกันระดับทหารด้วยการจัดเก็บแบบเย็น ประกัน และโปรโตคอลลายเซ็นหลายลายเซ็น',
      yield_generation: 'การสร้างผลตอบแทน',
      stake_metals: 'เดิมพันโลหะของคุณและรับรายได้แบบพาสซีฟ เปลี่ยนพอร์ตการลงทุนของคุณให้เป็นเครื่องมือทำกำไร',
      lightning_fast: 'เร็วปานสายฟ้า',
      fast_trading: 'การซื้อขาย 24/7 ด้วยการดำเนินการต่ำกว่าวินาที แพลตฟอร์มโลหะมีค่าที่เร็วที่สุดในโลก',
      always_available: 'พร้อมใช้งานเสมอ',
      trade_anytime: 'ซื้อขายได้ทุกที่ทุกเวลา แพลตฟอร์มของเราไม่เคยหลับใหล ดังนั้นโอกาสของคุณจึงไม่ต้องรอ',
      join_gold_rush: 'เข้าร่วมยุคตื่นทอง',
      dont_miss: 'อย่าพลาดโอกาสโลหะมีค่าที่ยิ่งใหญ่ที่สุดในทศวรรษนี้ เริ่มซื้อขายวันนี้',
      active_traders: '50,000+ ผู้ซื้อขายที่ใช้งานอยู่',
      volume_traded: 'ปริมาณการซื้อขายกว่า 2.8 พันล้านดอลลาร์',
      uptime: 'เวลาทำงาน 99.9%',
      eve_revolution: '🚀 ปฏิวัติ EVE',
      introducing_eve: 'ขอแนะนำ EVE Token',
      eve_subtitle: 'โทเค็นรางวัลการซื้อขายโลหะมีค่าแรกในโลก การซื้อขายทุกครั้งจะได้รับ EVE—ประตูสู่อนาคตของการเงินของคุณ',
      earn_eve: 'ได้รับ EVE Token',
      earn_eve_desc: 'รับ 100 EVE token สำหรับค่าธรรมเนียมการซื้อขายทุก $1 เปลี่ยนกิจกรรมการซื้อขายของคุณให้เป็นสินทรัพย์ดิจิทัลที่มีค่า',
      blockchain_ready: 'พร้อม Blockchain',
      blockchain_desc: 'EVE ถูกออกแบบมาเพื่ออนาคต การรวมบล็อกเชนแบบเต็มรูปแบบและความสามารถในการเก็บรักษาด้วยตนเองจะเปิดตัวเร็วๆ นี้',
      global_exchange: 'การจดทะเบียนในตลาดโลก',
      exchange_desc: 'แผนงานของเรารวมถึงการจดทะเบียน EVE ในตลาดหลักทรัพย์ใหญ่ๆ ทั่วโลก ปลดล็อคสภาพคล่องระดับโลกและมูลค่าตลาด',
      ecosystem_utility: 'ยูทิลิตี้ของระบบนิเวศ',
      utility_desc: 'ใช้ EVE เพื่อลดค่าธรรมเนียม การลงคะแนนเสียงในการกำกับดูแล และการเข้าถึงพิเศษไปยังฟีเจอร์และบริการระดับพรีเมียม',
      start_earning: 'เริ่มหา EVE',
      learn_about_eve: 'เรียนรู้เกี่ยวกับ EVE',
      eve_stats_earned: '2.5M+ EVE ที่ได้รับ',
      eve_stats_traders: '15,000+ ผู้ถือ EVE',
      eve_stats_value: 'เติบโตทุกวัน'
    },
    wallet: {
      title: 'กระเป๋าเงินพอร์ตโฟลิโอ',
      subtitle: 'จัดการโลหะมีค่าและสกุลเงินของคุณ',
      deposit: 'ฝากเงิน',
      kyc_required_tooltip: 'โปรดดำเนินการ KYC ให้เสร็จสิ้นเพื่อฝากเงิน',
      refresh: 'รีเฟรช',
      total_portfolio_value: 'มูลค่าพอร์ตโฟลิโอรวม',
      change_24h: 'การเปลี่ยนแปลง 24 ชั่วโมง',
      active_assets: 'สินทรัพย์ที่ใช้งานอยู่',
      asset_balances: 'ยอดคงเหลือสินทรัพย์',
      live_prices: 'ราคาสด',
      quick_actions: 'การดำเนินการด่วน',
      transaction_history: 'ประวัติการทำธุรกรรม',
      requests_title: 'คำขอฝาก/ถอนเงิน',
    },
    chatbot: {
      greeting_title: "สวัสดี! ฉันคือ",
      greeting_subtitle: "ผู้ช่วยส่วนตัวของคุณสำหรับวันนี้ ฉันจะช่วยอะไรคุณได้บ้าง",
      input_placeholder: "สอบถามเกี่ยวกับการซื้อขาย, สินเชื่อ, หรือ KYC..."
    },
    eve_token_modal: {
      title: "อนาคตของ EVE Token",
      description: "รางวัลของคุณเป็นมากกว่าโทเค็น—มันเป็นกุญแจสู่อนาคตของการเงิน",
      exchange_listing_title: "การจดทะเบียนในตลาดหลักทรัพย์",
      exchange_listing_desc: "เรากำลังอยู่ในภารกิจ! แผนงานของเรารวมถึงการจดทะเบียน EVE ในตลาดหลักทรัพย์ใหญ่ๆ ทั่วโลก ปลดล็อคมูลค่าตลาดที่แท้จริงและให้สภาพคล่องทั่วโลกแก่คุณ",
      blockchain_integration_title: "การรวมบล็อกเชน",
      blockchain_integration_desc: "EVE ถูกกำหนดมาเพื่อบล็อกเชน เรากำลังพัฒนาเทคโนโลยีเพื่อเปลี่ยน EVE ให้เป็นสินทรัพย์ที่กระจายอำนาจอย่างสมบูรณ์ ให้คุณสามารถดูแลรักษาด้วยตนเองและมีความสามารถบนเชน",
      global_utility_title: "ยูทิลิตี้ระดับโลก",
      global_utility_desc: "คิดให้ใหญ่ขึ้น EVE จะกลายเป็นเส้นเลือดใหญ่ของระบบนิเวศของเรา ใช้สำหรับค่าธรรมเนียมที่ลดลง สิทธิ์ในการกำกับดูแล และการเข้าถึงพิเศษไปยังฟีเจอร์และบริการระดับพรีเมียม รางวัลของคุณเป็นเพียงจุดเริ่มต้น",
      button_text: "ฟังดูน่าตื่นเต้น!"
    },
    us_stocks_guide: {
      tabs_intro: "หุ้บสหรัฐ 101",
      tabs_stocks: "ไดเรกทอรีหุ้บ",
      tabs_charts: "การวิเคราะห์ตลาด",
      tabs_qa: "ถาม-ตอบ",
      hero_badge: "EVE FINANCE · หุ้บสหรัฐ",
      hero_title: "ลงทุนในบริษัทที่ดีที่สุดของอเมริกา",
      hero_desc: "ซื้อขายหุ้บสหรัฐ 20 ตัวที่ดีที่สุดในรูปแบบโทเค็น — Apple, NVIDIA, Tesla, OpenAI และอื่นๆ — เริ่มต้นเพียง $10, 24/7, จากทุกที่บนโลก",
      stats_stocks: "หุ้บที่มีให้",
      stats_market_cap: "มูลค่าตลาดรวม",
      stats_min_invest: "การลงทุนขั้นต้ำ",
      stats_fee: "ค่าธรรมเนียมการซื้อขาย",
      what_is_stock_title: "หุ้บคืออะไร?",
      how_to_trade_title: "วิธีซื้อขายหุ้บสหรัฐบน EVE FINANCE",
      step1_title: "ฝาก USDT หรือก USD",
      step1_desc: "เติมเงินเข้ากระเป๋าของคุณด้วยการโอนเงินผ่านธนาคารหรอ USDT (ERC20/TRC20/SOL) ฝากขั้นต้ำ $50",
      step2_title: "ไปหน้าหุ้บสหรัฐ",
      step2_desc: "นำทางไปหน้าหุ้บสหรัฐจากแถบดานข้าง ดูราคาแบบเรียลไทม์",
      step3_title: "เลอกหุ้บและประเภทคำสั่ง",
      step3_desc: "เลอก Market Order เพื่อดำเนินการทันที หรอ Limit Order เพอกำหนดราคาเป้าหมายของคุณ",
      step4_title: "ใส่มูลค่าและยืนยัน",
      step4_desc: "ใสจำนวน USDT ที่ต้องการใช้ ตรวจสอบค่าธรรมเนียมและจำนวนหุ้บโดยประมาณ ยืนยันการซื้อขายของคุณ",
      step5_title: "ตดตามการถอหุ้บ",
      step5_desc: "หุ้บของคุณจะปรากฏในการถอหุ้บทันที กำไร/ขาดทุนอัพเดทแบบเรียลไทม์ตามราคาสด",
      market_order: "Market Order",
      market_order_desc: "ดำเนินการทันทีตามราคาตลาดปจจบัน เหมาะสำหรับการเข้าซื้อเรว",
      limit_order: "Limit Order",
      limit_order_desc: "กำหนดราคาเป้าหมายของคุณ เงินจะถูกแช่แข็งจนกวาจะถงราคาหรอยกเลิก",
      sectors_title: "ฉันสามารถลงทุนในอตุสาหกรรมอะไรได้บ้าง?",
      diversification_tip: "เคล็ดลบการกระจายการลงทุน",
      diversification_desc: "การกระจายการลงทุนทัวอตุสาหกรรมตางๆ ชวยลดความเสี่ยง เมอเทคโนโลยลดลง หุ้บผ้บรโภคอายทรงตว",
      risk_title: "ทำควาเขากับระดบความเสี่ยง",
      risk_disclaimer: "ผลการดำเนินงานในอดตไมใชการรบัรองผลลพัธในอนาคต การลงทนทังหมดมควาเสี่ยงตอการสญเสีย",
      search_placeholder: "ค้นหาดวยชอ สัญลักษณ์ หรออตุสาหกรรม…",
      sector_all: "ทังหมด",
      sector_tech: "เทคโนโลย",
      sector_ai: "AI",
      sector_crypto: "คริปโต",
      stocks_count: "หุ้บ",
      chart_market_cap: "มูลค่าตลาด (ลาน USD) — 10 อับดบแรก",
      chart_revenue: "การเตบโตของรายได้ 2020–2023 ($B)",
      chart_quality: "ปจจยคณภาพพอรต์ (เทคโนโลยสหรัฐ)",
      chart_sector: "การแบงอปตามอตุสาหกรรม — หุ้บจดทะเบียน",
      table_title: "เปรยบเทยบ Mega-Cap (6 อับดบแรก)",
      table_stock: "หุ้บ",
      table_market_cap: "มูลค่าตลาด",
      table_revenue: "รายได้",
      table_pe: "P/E",
      table_risk: "ความเสี่ยง",
      table_div: "เงินปันผล",
      faq_title: "คำถามทพบบอย",
      faq_subtitle: "ทกสงทคณตองการรเกยวกบการซอขายหุนสหรัฐบน EVE FINANCE",
      risk_disclosure_title: "การเปดเผยความเสี่ยงในการลงทุน",
      risk_disclosure_desc: "การซอขายหุนรปแบบโทเคนมความเสี่ยงสง รวมถงความเป็นไปไดทจะสญเสยการลงทุนทงหมดของคณ ราคาหุนสามารถผนผวนสงและไดรบผลกระทบจากสภาวะตลาด ผลการดำเนนงานของบริษัท ปจจยทางเศรษฐกจ และเหตการณทางภมรัฐศาสตร ผลการดำเนนงานในอดตไมไดบงชถงผลลพัธในอนาคต คมอเลมนี้มไวเพอวตถประสงคการศกษาเทานัน และไมถือเปนคำแนะนาด้านการลงทุน กรณาลงทนเฉพาะเงนทคณสามารถรบการสญเสยได และพจารณาปรกษานกวางแผนการเงนทไดรบใบอนญาต"
    }
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  // 从localStorage读取保存的语言设置，默认为英文
  const [language, setLanguage] = useState(() => {
    if (typeof window !== 'undefined') {
      return localStorage.getItem('eve-finance-language') || 'en';
    }
    return 'en';
  });

  // 当语言改变时，保存到localStorage
  useEffect(() => {
    if (typeof window !== 'undefined') {
      localStorage.setItem('eve-finance-language', language);
    }
  }, [language]);

  const t = (key) => {
    const keys = key.split('.');
    let result = translations[language];
    for (const k of keys) {
      result = result?.[k];
      if (result === undefined) {
        // Fallback to English if translation is missing
        let fallback = translations['en'];
        for (const fk of keys) {
          fallback = fallback?.[fk];
        }
        return fallback || key;
      }
    }
    return result;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);